### PR TITLE
Add yaml install to transfer-rendered-files.yml

### PR DESCRIPTION
**Pull request by cansavvy**
This fix unfortunately could not be synced or else repo specific information would be overwritten (a problem I still want to figure out how to circumvent). 

But its the same fix I ended up making on the template repository: https://github.com/jhudsl/DaSL_Course_Template_Bookdown/blob/eee84ca104d4c827aafd8e1ce863bb35e4ad8ded/.github/workflows/transfer-rendered-files.yml#L39

Related to https://github.com/jhudsl/DaSL_Course_Template_Bookdown/pull/215

### CODE REVIEW

**Comment by cansavvy** [comment]
Saw there were some spelling errors so I addressed those by either fixing them or adding them to the dictionary.txt

**Comment by cansavvy** [comment]
Not sure why the `docs/about.Rmd` file is gone, but when we re-render it should be back anyway. Git was being really weird about it with the About.Rmd vs about.Rmd files.

**Comment by carriewright11** [comment]
> Not sure why the `docs/about.Rmd` file is gone, but when we re-render it should be back anyway. Git was being really weird about it with the About.Rmd vs about.Rmd files.

hmm maybe I should rename?

**Comment by cansavvy** [comment]
> hmm maybe I should rename?

Not sure why it was being weird. But whatever you go with make sure it's consistent with the _bookdown.yml of course.

**Pull request merged**
